# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convolve two numeric vectors and return the resuting vector.
#'
#' The convolution of two vectors \eqn{a} of length \eqn{n_1} and
#' and \eqn{b} of length \eqn{n_2} is of length \eqn{n_1 + n_2 - 1}.
#'
#' @param a the first vector
#' @param b the second vector
#'
#' @return a new vector that the convolution
#' @export
#'
#' @examples
#' base::set.seed(1)
#' ourConvolve(a = rnorm(2), b = rnorm(3))
#'
ourConvolve <- function(a, b) {
    .Call('_stat290_ass2_ourConvolve', PACKAGE = 'stat290.ass2', a, b)
}

