// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppUniform.h"
#include <Rcpp.h>

using namespace Rcpp;

// Unew
XPtr<Uniform> Unew(SEXP min, SEXP max);
RcppExport SEXP _RcppUniform_Unew(SEXP minSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type min(minSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(Unew(min, max));
    return rcpp_result_gen;
END_RCPP
}
// Udraw
NumericVector Udraw(SEXP xp, SEXP n);
RcppExport SEXP _RcppUniform_Udraw(SEXP xpSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(Udraw(xp, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppUniform_Unew", (DL_FUNC) &_RcppUniform_Unew, 2},
    {"_RcppUniform_Udraw", (DL_FUNC) &_RcppUniform_Udraw, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppUniform(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
