# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Unew <- function(min, max) {
    .Call(`_RcppUniform_Unew`, min, max)
}

Udraw <- function(xp, n) {
    .Call(`_RcppUniform_Udraw`, xp, n)
}

